name: Publish to Comfy registry
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"
      - ".github/workflows/publish-comfyui.yml"

jobs:
  publish-node:
    name: Publish Custom Node ComfyUI Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@main
        with:
          personal_access_token: ${{ secrets.COMFYUI_REGISTRY_TOKEN }}
