name: Publish npm package
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/comfyui-api-nodes/package.json"
      - ".github/workflows/publish-npm-package.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "21.x"
          registry-url: "https://registry.npmjs.org"
      - run: cd ./packages/comfyui-api-nodes && npm clean-install
      - run: cd ./packages/comfyui-api-nodes && npm publish --provenance --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
